PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Quotes(quote text not null, id int not null primary key, source text not null, usage int not null);
INSERT INTO Quotes VALUES('Never put off till to-morrow what you can do to-day.',1,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('Never trouble another for what you can do yourself. ',2,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('Never spend your money before you have it.',3,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('Never buy what you do not want, because it is cheap; it will be dear to you.',4,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('Pride costs us more than hunger, thirst, and cold.',5,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('We never repent of having eaten too little.',6,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('Nothing is troublesome that we do willingly.',7,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('How much pain have cost us the evils which have never happened.',8,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('Take things always by their smooth handle.',9,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('When angry, count ten, before you speak; if very angry, a hundred.',10,'Thomas Jefferson',0);
INSERT INTO Quotes VALUES('It is better to offer no excuse than a bad one. ',11,'George Washington',0);
INSERT INTO Quotes VALUES('It is better to be alone than in bad company. ',12,'George Washington',0);
INSERT INTO Quotes VALUES('If freedom of speech is taken away, then dumb and silent we may be led, like sheep to the slaughter.',13,'George Washington',0);
INSERT INTO Quotes VALUES('But lest some unlucky event should happen unfavorable to my reputation, I beg it may be remembered by every gentleman in the room that I this day declare with the utmost sincerity, I do not think myself equal to the command I am honored with.',14,'George Washington',0);
INSERT INTO Quotes VALUES('A primary object should be the education of our youth in the science of government. In a republic, what species of knowledge can be equally important? And what duty more pressing than communicating it to those who are to be the future guardians of the liberties of the country?',15,'George Washington',0);
INSERT INTO Quotes VALUES('Be courteous to all, but intimate with few, and let those few be well tried before you give them your confidence. True friendship is a plant of slow growth, and must undergo and withstand the shocks of adversity before it is entitled to appellation.',16,'George Washington',1);
INSERT INTO Quotes VALUES('A free people ought not only to be armed, but disciplined; to which end a uniform and well-digested plan is requisite; and their safety and interest require that they should promote such manufactories as tend to render them independent of others for essential, particularly military, supplies.',17,'George Washington',0);
INSERT INTO Quotes VALUES('Human happiness and moral duty are inseparably connected.',18,'George Washington',0);
INSERT INTO Quotes VALUES('However [political parties] may now and then answer popular ends, they are likely in the course of time and things, to become potent engines, by which cunning, ambitious, and unprincipled men will be enabled to subvert the power of the people and to usurp for themselves the reins of government, destroying afterwards the very engines which have lifted them to unjust dominion.',19,'George Washington',0);
INSERT INTO Quotes VALUES('99% of failures come from people who make excuses.',20,'George Washington',0);
INSERT INTO Quotes VALUES('Guard against the impostures of pretended patriotism.',21,'George Washington',0);
INSERT INTO Quotes VALUES('Labor to keep alive in your breast that little spark of celestial fire called conscience.',22,'George Washington',0);
INSERT INTO Quotes VALUES('Perseverance and spirit have done wonders in all ages.',23,'George Washington',0);
INSERT INTO Quotes VALUES('Associate yourself with men of good quality, if you esteem your own reputation; for ‘tis better to be alone than in bad company.',24,'George Washington',0);
INSERT INTO Quotes VALUES('Few men have virtue to withstand the highest bidder.',25,'George Washington',0);
INSERT INTO Quotes VALUES('Happiness depends more upon the internal frame of a person’s own mind, than on the externals in the world.',26,'George Washington',0);
INSERT INTO Quotes VALUES('Experience teaches us that it is much easier to prevent an enemy from posting themselves than it is to dislodge them after they have got possession. ',27,'George Washington',0);
INSERT INTO Quotes VALUES('The harder the conflict, the greater the triumph',28,'George Washington',0);
INSERT INTO Quotes VALUES('Worry is the interest paid by those who borrow trouble.',29,'George Washington',0);
INSERT INTO Quotes VALUES('The turning points of lives are not the great moments. The real crises are often concealed in occurrences so trivial in appearance that they pass unobserved.',30,'George Washington',0);
INSERT INTO Quotes VALUES('Real men despise battle, but will never run from it.',31,'George Washington',0);
INSERT INTO Quotes VALUES('Discipline is the soul of an army. It makes small numbers formidable; procures success to the weak, and esteem to all.',32,'George Washington',0);
INSERT INTO Quotes VALUES('Citizens by birth or choice of a common country, that country has a right to concentrate your affections. The name of American, which belongs to you, in your national capacity, must always exalt the just pride of Patriotism, more than any appellation derived from local discriminations.',33,'George Washington',0);
INSERT INTO Quotes VALUES('We should not look back unless it is to derive useful lessons from past errors, and for the purpose of profiting by dearly bought experience.',34,'George Washington',0);
INSERT INTO Quotes VALUES('I read my eyes out and can''t read half enough...the more one reads the more one sees we have to read.',35,'John Adams',0);
INSERT INTO Quotes VALUES('Let us tenderly and kindly cherish therefore, the means of knowledge. Let us dare to read, think, speak, and write.',36,'John Adams',0);
INSERT INTO Quotes VALUES('Facts are stubborn things; and whatever may be our wishes, our inclinations, or the dictates of our passion, they cannot alter the state of facts and evidence.',37,'John Adams',0);
INSERT INTO Quotes VALUES('A Constitution of Government once changed from Freedom, can never be restored. Liberty, once lost, is lost forever.',38,'John Adams',0);
INSERT INTO Quotes VALUES('The longer I live, the more I read, the more patiently I think, and the more anxiously I inquire, the less I seem to know...Do justly. Love mercy. Walk humbly. This is enough.',39,'John Adams',0);
INSERT INTO Quotes VALUES('There is nothing which I dread so much as a division of the republic into two great parties, each arranged under its leader, and concerting measures in opposition to each other. This, in my humble apprehension, is to be dreaded as the greatest political evil under our Constitution.',40,'John Adams',0);
INSERT INTO Quotes VALUES('Posterity! you will never know how much it cost the present generation to preserve your freedom! I hope you will make a good use of it.',41,'John Adams',0);
INSERT INTO Quotes VALUES('I say, that Power must never be trusted without a check.',42,'John Adams',0);
INSERT INTO Quotes VALUES('Children should be educated and instructed in the principles of freedom. Aristotle speaks plainly to this purpose, saying, ''that the institution of youth should be accommodated to that form of government under which they live; forasmuch as it makes exceedingly for the preservation of the present government, whatsoever it be.',43,'John Adams',0);
INSERT INTO Quotes VALUES('Let the human mind loose. It must be loose. It will be loose. Superstition and dogmatism cannot confine it.',44,'John Adams',0);
INSERT INTO Quotes VALUES('I must judge for myself, but how can I judge, how can any man judge, unless his mind has been opened and enlarged by reading.',45,'John Adams',0);
INSERT INTO Quotes VALUES('To believe all men honest is folly. To believe none is something worse.',46,'John Adams',1);
INSERT INTO Quotes VALUES('Government has no right to hurt a hair on the head of an Atheist for his Opinions. Let him have a care of his Practices.',47,'John Adams',0);
INSERT INTO Quotes VALUES('You will never be alone with a poet in your pocket.',48,'John Adams',0);
INSERT INTO Quotes VALUES('The way to secure liberty is to place it in the people''s hands, that is, to give them the power at all times to defend it in the legislature and in the courts of justice.',49,'John Adams',0);
INSERT INTO Quotes VALUES('There is danger from all men. The only maxim of a free government ought to be to trust no man living with power to endanger the public liberty.',50,'John Adams',0);
INSERT INTO Quotes VALUES('The happiness of society is the end of government.',51,'John Adams',0);
INSERT INTO Quotes VALUES('Be not intimidated...nor suffer yourselves to be wheedled out of your liberties by any pretense of politeness, delicacy, or decency. These, as they are often used, are but three different names for hypocrisy, chicanery and cowardice.',52,'John Adams',0);
INSERT INTO Quotes VALUES('And liberty cannot be preserved without a general knowledge among the people who have a right from the frame of their nature to knowledge...',53,'John Adams',0);
INSERT INTO Quotes VALUES('Without the pen of Paine, the sword of Washington would have been wielded in vain.',54,'John Adams',0);
INSERT INTO Quotes VALUES('Laws for the liberal education of youth, especially of the lower class of people, are so extremely wise and useful, that, to a humane and generous mind, no expense for this purpose would be thought extravagant.',55,'John Adams',0);
INSERT INTO Quotes VALUES('Old minds are like old horses; you must exercise them if you wish to keep them in working order.',56,'John Adams',0);
INSERT INTO Quotes VALUES('Nineteen twentieths of [mankind is] opaque and unenlightened. Intimacy with most people will make you acquainted with vices and errors and follies enough to make you despise them.',57,'John Adams',0);
INSERT INTO Quotes VALUES('If worthless men are sometimes at the head of affairs, it is, I believe, because worthless men are at the tail and the middle',58,'John Adams',1);
INSERT INTO Quotes VALUES('When legislature is corrupted, the people are undone.',59,'John Adams',0);
INSERT INTO Quotes VALUES('The true source of our sufferings has been our timidity.',60,'John Adams',0);
INSERT INTO Quotes VALUES('Everything in life should be done with reflection.',61,'John Adams',0);
INSERT INTO Quotes VALUES('Great is the guilt of an unnecessary war.',62,'John Adams',0);
INSERT INTO Quotes VALUES('The jaws of power are always open to devour, and her arm is always stretched out, if possible, to destroy the freedom of thinking, speaking, and writing.',63,'John Adams',0);
INSERT INTO Quotes VALUES('Abuse of words has been the great instrument of sophistry and chicanery, of party, faction, and division of society.',64,'John Adams',0);
INSERT INTO Quotes VALUES('Property monopolized or in the possession of a few is a curse to mankind.',65,'John Adams',0);
INSERT INTO Quotes VALUES('Work smarter, not harder — something we should''ve followed more when making this.',66,'QB Devs',0);
INSERT INTO Quotes VALUES('Always make sure you know what work the other people in a group project will do before starting work on the project.',67,'QB Devs',0);
INSERT INTO Quotes VALUES('He seemed so devoted — a very slave — and there was a certain latent intensity in that love which had fascinated her.',68,'Scarlet Pimpernel by Baroness Orczy',0);
INSERT INTO Quotes VALUES('Thus human beings judge of one another, superficially, casually, throwing contempt on one another, with but little reason, and no charity.',69,'Scarlet Pimpernel by Baroness Orczy',0);
INSERT INTO Quotes VALUES('He was calmly eating his soup, laughing with pleasant good-humour, as if he had come all the way to Calais for the express purpose of enjoying supper at this filthy inn, in the company of his arch-enemy.',70,'Scarlet Pimpernel by Baroness Orczy',0);
INSERT INTO Quotes VALUES('Those friends who knew, laughed to scorn the idea that Marguerite St. Just had married a fool for the sake of the worldly advantages with which he might endow her. They knew, as a matter of fact, that Marguerite St. Just cared nothing about money, and still less about a title.',71,'Scarlet Pimpernel by Baroness Orczy',0);
INSERT INTO Quotes VALUES('"Money and titles may be hereditary," she would say, "but brains are not."',72,'Scarlet Pimpernel by Baroness Orczy',0);
INSERT INTO Quotes VALUES('We seek him here, we seek him there, Those Frenchies seek him everywhere. Is he in heaven? — Is he in hell? That demmed, elusive Pimpernel?',73,'Scarlet Pimpernel by Baroness Orczy',0);
INSERT INTO Quotes VALUES('How that stupid, dull Englishman ever came to be admitted within the intellectual circle which revolved round “the cleverest woman in Europe,” as her friends unanimously called her, no one ventured to guess—a golden key is said to open every door, asserted the more malignantly inclined.',74,'Scarlet Pimpernel by Baroness Orczy',0);
INSERT INTO Quotes VALUES('This is an example.',75,'QB Devs',0);
INSERT INTO Quotes VALUES('Ask not what your country can do for you; ask what you can do for your country.',76,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('If not us, who? If not now, when?',77,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('Every accomplishment starts with the decision to try.',78,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('As we express our gratitude, we must never forget that the highest form of appreciation is not to utter words, but to live by them.',79,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('Those who dare to fail miserably can achieve greatly.',80,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('The ignorance of one voter in a democracy impairs the security of all.',81,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('Do not pray for easy lives, pray to be stronger men.',82,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('Leadership and learning are indispensable to each other.',83,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('Life is never easy. There is work to be done and obligations to be met—obligations to truth, to justice, and to liberty.',84,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('Too often we enjoy the comfort of opinion without the discomfort of thought.',85,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('We have the power to make this the best generation of mankind in the history of the world or make it the last.',86,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('The greater our knowledge increases the more our ignorance unfolds.',87,'John F. Kennedy',0);
INSERT INTO Quotes VALUES('There''s not a liberal America and a conservative America — there''s the United States of America.',88,'Barack Obama',0);
INSERT INTO Quotes VALUES('Change will not come if we wait for some other person or if we wait for some other time. We are the ones we''ve been waiting for. We are the change that we seek.',89,'Barack Obama',0);
INSERT INTO Quotes VALUES('Where we are met with cynicism and doubts and those who tell us that we can''t, we will respond with that timeless creed that sums up the spirit of a people: Yes, we can.',90,'Barack Obama',0);
INSERT INTO Quotes VALUES('Clear-eyed, we can understand that there will be war, and still strive for peace.',91,'Barack Obama',0);
INSERT INTO Quotes VALUES('With eyes fixed on the horizon and God''s grace upon us, we carried forth that great gift of freedom and delivered it safely to future generations.',92,'Barack Obama',0);
INSERT INTO Quotes VALUES('There has been one constant amidst these shifting tides. At every turn, America''s men and women in uniform have served with courage and resolve.',93,'Barack Obama',0);
INSERT INTO Quotes VALUES('We should do everything we can to make sure this country lives up to our children''s expectations.',94,'Barack Obama',0);
INSERT INTO Quotes VALUES('As it has for more than two centuries, progress will come in fits and starts. It''s not always a straight line. It''s not always a smooth path.',95,'Barack Obama',0);
INSERT INTO Quotes VALUES('The strongest weapon against hateful speech is not repression; it is more speech.',96,'Barack Obama',0);
INSERT INTO Quotes VALUES('The cynics may be the loudest voices, — but I promise you, they will accomplish the least.',97,'Barack Obama',0);
INSERT INTO Quotes VALUES('We choose hope over fear. We see the future not as something out of our control, but as something we can shape for the better through concerted and collective effort.',98,'Barack Obama',0);
INSERT INTO Quotes VALUES('To be an American is about something more than what we look like, or what our last names are, or how we worship.',99,'Barack Obama',0);
INSERT INTO Quotes VALUES('It is you, the young and fearless at heart, the most diverse and educated generation in our history, who the nation is waiting to follow.',100,'Barack Obama',0);
INSERT INTO Quotes VALUES('No matter who you are or what you look like, how you started off, or how and who you love, America is a place where you can write your own destiny.',101,'Barack Obama',0);
INSERT INTO Quotes VALUES('That''s the America I know. That''s the country we love. Clear-eyed. Big-hearted. Undaunted by challenge.',102,'Barack Obama',0);
INSERT INTO Quotes VALUES('The long sweep of America has been defined by forward motion, a constant widening of our founding creed to embrace all and not just some.',103,'Barack Obama',0);
INSERT INTO Quotes VALUES('To quote or not to quote, that is the question.',104,'QB Devs',0);
INSERT INTO Quotes VALUES('Men give me credit for some genius. All the genius I have lies in this; when I have a subject in hand, I study it profoundly. Day and night it is before me. My mind becomes pervaded with it. Then the effort that I have made is what people are pleased to call the fruit of genius. It is the fruit of labor and thought.',106,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('Those who stand for nothing fall for everything.',107,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('Give all the power to the many, they will oppress the few. Give all the power to the few, they will oppress the many.',108,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('The constitution shall never be construed...to prevent the people of the United States who are peaceable citizens from keeping their own arms.',109,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('A well adjusted person is one who makes the same mistake twice without getting nervous.',110,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('The art of reading is to skip judiciously.',111,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('I never expect a perfect work from an imperfect man.',112,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('A nation which can prefer disgrace to danger is prepared for a master, and deserves one.',113,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('There are seasons in every country when noise and impudence pass current for worth; and in popular commotions especially, the clamors of interested and factious men are often mistaken for patriotism.',114,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('The sacred rights of mankind are not to be rummaged for among old parchments or musty records. They are written, as with a sunbeam, in the whole volume of human nature, by the Hand of Divinity itself, and can never be erased or obscured by mortal power.',115,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('Hard words are very rarely useful. Real firmness is good for every thing. Strut is good for nothing.',116,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('I have thought it my duty to exhibit things as they are, not as they ought to be.',117,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('Men are reasoning rather than reasonable animals.',118,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('Who talks most about freedom and equality? Is it not those who hold the bill of rights in one hand and a whip for affrighted slaves in the other?',119,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('The best we can hope for concerning the people at large is that they be properly armed.',120,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('A powerful, victorious ally is yet another name for master.',121,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('For in politics, as in religion, it is equally absurd to aim at making proselytes by fire and sword. Heresies in either can rarely be cured by persecution.',122,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('If we must have an enemy at the head of government, let it be one whom we can oppose, and for whom we are not responsible.',123,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('Vigor of government is essential to the security of liberty.',124,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('It will be of little avail to the people, that the laws are made by men of their own choice, if the laws be so voluminous that they cannot be read, or so incoherent that they cannot be understood',125,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('The inquiry constantly is what will please, not what will benefit the people. In such a government there can be nothing but temporary expedient, fickleness, and folly.',126,'Alexander Hamilton',0);
INSERT INTO Quotes VALUES('The mark of a pro coder is `Build Passing`',127,'QB Devs',0);
INSERT INTO Quotes VALUES('If a teacher gives you several days for an assignment, there is a reason for that; there is a lot of work.',128,'QB Devs',0);
INSERT INTO Quotes VALUES('You can’t let your failures define you. You have to let your failures teach you.',105,'Barack Obama',0);
INSERT INTO Quotes VALUES('Folks are usually about as happy as they make their minds up to be.',129,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Whatever you are, be a good one.',130,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Do I not destroy my enemies when I make them my friends?',131,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('America will never be destroyed from the outside. If we falter and lose our freedoms, it will be because we destroyed ourselves.',132,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('My Best Friend is a person who will give me a book I have not read.',133,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Nearly all men can stand adversity, but if you want to test a man''s character, give him power.',134,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('I''m a success today because I had a friend who believed in me and I didn''t have the heart to let him down.',135,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Books serve to show a man that those original thoughts of his aren''t very new after all.',136,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Those who deny freedom to others, deserve it not for themselves.',137,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Whenever I hear anyone arguing for slavery, I feel a strong impulse to see it tried on him personally.',138,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Those who look for the bad in people will surely find it.',139,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('I am not bound to win, but I am bound to be true. I am not bound to succeed, but I am bound to live up to what light I have.',140,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Be sure you put your feet in the right place, then stand firm.',141,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('You can fool some of the people all of the time, and all of the people some of the time, but you can not fool all of the people all of the time.',142,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('I would rather be a little nobody, then to be a evil somebody',143,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Character is like a tree and reputation its shadow. The shadow is what we think it is and the tree is the real thing.',144,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Always bear in mind that your own resolution to succeed is more important than any one thing.',145,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('The best way to predict your future is to create it.',146,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Elections belong to the people. It''s their decision. If they decide to turn their back on the fire and burn their behinds, then they will just have to sit on their blisters.',147,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('Give me six hours to chop down a tree and I will spend the first four sharpening the axe.',148,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('No man has a good enough memory to be a successful liar.',149,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('The best thing about the future is that it comes one day at a time.',150,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('I have always found that mercy bears richer fruits than strict justice.',151,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('I care not for a man''s religion whose dog and cat are not the better for it.',152,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('You cannot escape the responsibility of tomorrow by evading it today.',153,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('I do not think much of a man who is not wiser today than he was yesterday.',154,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('You have to do your own growing no matter how tall your grandfather was.',155,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('You cannot help people permanently by doing for them, what they could and should do for themselves.',156,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('You can tell the greatness of a man by what makes him angry.',157,'Abraham Lincoln',0);
INSERT INTO Quotes VALUES('When something is important enough, you do it even if the odds are not in your favor.',158,'Elon Musk',0);
INSERT INTO Quotes VALUES('If you get up in the morning and think the future is going to be better, it is a bright day. Otherwise, it''s not.',159,'Elon Musk',0);
INSERT INTO Quotes VALUES('There have to be reasons that you get up in the morning and you want to live. Why do you want to live? What''s the point? What inspires you? What do you love about the future? If the future does not include being out there among the stars and being a multi-planet species, I find that incredibly depressing.',160,'Elon Musk',0);
INSERT INTO Quotes VALUES('When Henry Ford made cheap, reliable cars, people said, ''Nah, what''s wrong with a horse?'' That was a huge bet he made, and it worked.',161,'Elon Musk',0);
INSERT INTO Quotes VALUES('Persistence is very important. You should not give up unless you are forced to give up.',162,'Elon Musk',0);
INSERT INTO Quotes VALUES('It''s OK to have your eggs in one basket as long as you control what happens to that basket.',163,'Elon Musk',0);
INSERT INTO Quotes VALUES('If you go back a few hundred years, what we take for granted today would seem like magic-being able to talk to people over long distances, to transmit images, flying, accessing vast amounts of data like an oracle. These are all things that would have been considered magic a few hundred years ago.',164,'Elon Musk',0);
INSERT INTO Quotes VALUES('The first step is to establish that something is possible; then probability will occur.',165,'Elon Musk',0);
INSERT INTO Quotes VALUES('I think it is possible for ordinary people to choose to be extraordinary.',166,'Elon Musk',0);
INSERT INTO Quotes VALUES('I could either watch it happen or be a part of it.',167,'Elon Musk',0);
INSERT INTO Quotes VALUES('Do one thing every day that scares you.',168,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('Do what you feel in your heart to be right – for you’ll be criticized anyway.',169,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('The future belongs to those who believe in the beauty of their dreams.',170,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.',171,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('Many people will walk in and out of your life, but only true friends will leave footprints in your heart.',172,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('We are afraid to care too much, for fear that the other person does not care at all.',173,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('To handle yourself, use your head; to handle others, use your heart.',174,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('You can often change your circumstances by changing your attitude.',175,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('If someone betrays you once, it’s their fault; if they betray you twice, it’s your fault.',176,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('With the new day comes new strength and new thoughts.',177,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('Happiness is not a goal...it''s a by-product of a life well lived.',178,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('Life was meant to be lived, and curiosity must be kept alive. One must never, for whatever reason, turn his back on life.',179,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('It is not fair to ask of others what you are not willing to do yourself.',180,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('You have to accept whatever comes, and the only important thing is that you meet it with the best you have to give.',181,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('In the long run, we shape our lives, and we shape ourselves. The process never ends until we die. And the choices we make are ultimately our own responsibility.',182,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('Friendship with oneself is all important, because without it one cannot be friends with anyone else in the world.',183,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('Never allow a person to tell you no who doesn''t have the power to say yes.',184,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('Never mistake knowledge for wisdom. One helps you make a living; the other helps you make a life.',185,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('No one won the last war, and no one will win the next war.',186,'Eleanor Roosevelt',0);
INSERT INTO Quotes VALUES('When will our consciences grow so tender that we will act to prevent human misery rather than avenge it?',187,'Eleanor Roosevelt',0);
CREATE UNIQUE INDEX main_quotes on Quotes(quote);
COMMIT;
