# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}
    - name: Look for JS errors and show how to fix them
      run: |
        echo -e "\033[0;36m" Installing modules...
        npm ci
        echo -e "\033[0;36m" Number of quotes:
        npm run count
        echo -e "\033[0;36m" Installing jsonlint...
        sudo npm i -g jsonlint
        echo -e "\033[0;36m" Checking for code errors...
        for i in *.js db/*.js; do npx eslint $i; npx eslint --fix-dry-run $i; done; for i in *.json; do jsonlint -q $i; done
    
      #  git checkout -b origin/$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format='%(refname:short)' | head -1) 
      #  git log | head -1 | sed 's/commit//g' 
    - name: Notify if the code is broken
      uses: sarisia/actions-status-discord@v1.8.5
      if: failure()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
