# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Look for JS errors and show how to fix them
      run: |
        echo "\u001b[36m" Number of quotes:
        npm run count
        echo "\u001b[36m" Installing eslint and jsonlint...
        npm i eslint; sudo npm i -g jsonlint
        echo "\u001b[36m" Checking for code errors...
        for i in *.js; do npx eslint $i; npx eslint --fix-dry-run $i; done; for i in *.json; do jsonlint -q $i; done
    - name: Dump the SQLite
      run: for i in ./db/*.db; do sqlite3 $i .dump > $i.dump; done
      #  git checkout -b origin/$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format='%(refname:short)' | head -1) 
      #  git log | head -1 | sed 's/commit//g' 
    - name: Notify if the code is broken
      uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}