# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master, gl ]
  pull_request:
    branches: [ master, gl ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Look for errors and show how to fix them
      run: |
        npm install eslint
        npx eslint index.js; npx eslint --fix-dry-run
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Notify
        # You may pin to the exact commit or the version.
        # uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          # Discord webhook URL. Should be stored in a secret and inserted as a context expression.
          webhookUrl: {{ secrets.DISCORD_WEBHOOK }}
          # Severity level - info, warn, or error
          severity: war
