# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master, gl ]
  pull_request:
    branches: [ master, gl ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Look for errors and show how to fix them
      run: |
        npm install eslint
        npx eslint index.js; npx eslint --fix-dry-run
        
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: always()
        with:
            severity: error
            details: Test Failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test failure 2
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
