name: Update the copy of the wiki on the website

on:
  schedule:
      - cron: 30 1 * * *
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Update submodules
      run: chmod +x ./wiki_upd.sh && bash ./wiki_upd.sh
    - name: Commit the new submodule
      uses: stefanzweifel/git-auto-commit-action@1f4914882d31162256a5dd23dd006bf97be303a2
      with:
        commit_message: Update the wiki copy
        file_pattern: 'wiki/*'
    - name: Notify if the code is broken
      uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}